version: "3.9"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.102.4
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      # Optional: Set n8n URL (needed if running behind proxy or SSL)
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      # Execution timeout set to 2 minutes
      - N8N_EXECUTIONS_TIMEOUT=120
volumes:
  n8n_data:
