---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mcp-server-elasticsearch
spec:
  type: library
  owner: group:devtools-team
  lifecycle: beta

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-mcp-server-elasticsearch
  description: Buildkite Pipeline for mcp-server-elasticsearch
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/mcp-server-elasticsearch

spec:
  type: buildkite-pipeline
  owner: group:devtools-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: mcp-server-elasticsearch
      description: Run checks for the mcp-server-elasticsearch package
    spec:
      repository: elastic/mcp-server-elasticsearch
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        devtools-team:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mcp-server-elasticsearch-docker
  description: Build and publish Docker images for mcp-server-elasticsearch
spec:
  type: buildkite-pipeline
  owner: group:devtools-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: mcp-server-elasticsearch-docker
      description: Build and publish Docker images for mcp-server-elasticsearch
    spec:
      repository: elastic/mcp-server-elasticsearch
      pipeline_file: ".buildkite/docker.yml"
      teams:
        devtools-team:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      provider_settings:
        build_pull_requests: false
        build_branches: false
        build_tags: true
      cancel_intermediate_builds: true
